# Generated by Django 3.0.2 on 2020-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title', max_length=80)),
                ('text', models.TextField(help_text='Enter the text')),
                ('pubDate', models.DateTimeField()),
            ],
        ),
    ]
